version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
networks:
  internal:
    name: internal
    driver: bridge
